server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: always

indexing-settings:
  sites:
    - url: http://portsurgut.ru/
      name: PORT
#     pages - 158, lemmas - 21431
    - url: https://www.svetlovka.ru/
      name: SVETLOVKA
#     pages - 228, lemmas - 122082
    - url: https://et-cetera.ru/mobile/
      name: ET-CETERA
#     pages - 50, lemmas - 41905
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referer: https://www.google.com